name: Helm Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  helm_deploy:
    name: Deploy to Kubernetes with Helm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.21.0'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.7.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Helm Upgrade
        working-directory: {{ helm_directory }}
        run: |
          helm upgrade --install my-release . --namespace my-namespace
          kubectl rollout status deployment/my-release -n my-namespace