name: Terraform Deployment - {{ module_name }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Init, Fmt, Plan, and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: {{ terraform_directory }}
        run: terraform init

      - name: Terraform Fmt
        working-directory: {{ terraform_directory }}
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: {{ terraform_directory }}
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: {{ terraform_directory }}
        run: terraform apply -auto-approve